### ISSUE TITLE
How to scroll back?

### ISSUE THREAD

**Issue by binaryphile** [grahamking/hatcog#17]
Sorry for the basic question in a github issue.  A reference to a doc that answers the simple ones would be fine.

I wanted to try hatcog because I was looking for a client that left all of the window manipulation to tmux, since I already know how to split, join etc in that environment.

I figured a tmux-friendly client would allow me to use the pageback scrolling of tmux as well, but I don't think hatcog is letting me do that, probably because it's curses-based.  So what is the key to scroll backward in hatcog?

Does this mean backward search in tmux won't work either?

**Comment by grahamking** [comment]
PageUp key, that's all. Just press PageUp, no escape, no tmux key, just PageUp.

It writes out the buffer into a text file and runs it through your pager (`less` usually). Exit less to return to hatcog.

I don't think we can use tmux's buffer, because hatcog is curses. I figured using less was the next best thing :-)
